<div class="container-fluid">
    <div class="row">
        <center><h1>ENCRIPTACION</h1></center>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6">
            <b><?= 'Patron MD5' . ' ' . md5($clave) ?></b><hr>
            <b><?= 'Patron SHA1' . ' ' . sha1($clave) ?></b><hr>
            <b><?= 'patron con cambio de encripcion' . ' ' . password_hash($clave, PASSWORD_DEFAULT) ?></b><hr>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
    </div>
</div>