<div class="container-fluid">
    <div class="row">
        <center><h1>Aprendiento Arrays y mostrandolo en tablas</h1></center>
    </div>
    <div class="row m-5">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <table class="table table-hover table-responsive border shadow">
                
                <head>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Correo</th>
                    </tr>
                </head>
                <tbody>
                    <?php foreach ($Usuarios as $key) { ?>
                        <tr>
                            <td><?= $key['Nombre'] ?></td>
                            <td><?= $key['Apellido'] ?></td>
                            <td><a href="mailto:<?= $key['Correo'] ?>"><?= $key['Correo'] ?></a></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
    </div>
</div>